import { ContentType, CourseType, IHomeworkSubmitAttachment, Language, QuestionnaireType } from './types';
export declare const ID_PREFIX = "https://id.tsinghua.edu.cn";
export declare const LEARN_PREFIX = "https://learn.tsinghua.edu.cn";
export declare const REGISTRAR_PREFIX = "https://zhjw.cic.tsinghua.edu.cn";
export declare const ID_LOGIN: () => string;
export declare const ID_LOGIN_CHECK: () => string;
export declare const LEARN_AUTH_ROAM: (ticket: string) => string;
export declare const LEARN_LOGOUT: () => string;
export declare const LEARN_HOMEPAGE: (courseType: CourseType) => "https://learn.tsinghua.edu.cn/f/wlxt/index/course/student/" | "https://learn.tsinghua.edu.cn/f/wlxt/index/course/teacher/";
export declare const LEARN_STUDENT_COURSE_LIST_PAGE: () => string;
export declare const LEARN_SEMESTER_LIST: () => string;
export declare const LEARN_CURRENT_SEMESTER: () => string;
export declare const LEARN_COURSE_LIST: (semester: string, courseType: CourseType, lang: Language) => string;
export declare const LEARN_COURSE_PAGE: (courseID: string, courseType: CourseType) => string;
export declare const LEARN_COURSE_TIME_LOCATION: (courseID: string) => string;
export declare const LEARN_FILE_LIST: (courseID: string, courseType: CourseType) => string;
export declare const LEARN_FILE_CATEGORY_LIST: (courseID: string, courseType: CourseType) => string;
export declare const LEARN_FILE_LIST_BY_CATEGORY_STUDENT: (courseID: string, categoryId: string) => string;
export declare const LEARN_FILE_LIST_BY_CATEGORY_TEACHER = "https://learn.tsinghua.edu.cn/b/wlxt/kj/v_kjxxb_wjwjb/teacher/pageList";
export declare const LEARN_FILE_LIST_BY_CATEGORY_TEACHER_FORM_DATA: (courseID: string, categoryId: string) => FormData;
export declare const LEARN_FILE_DOWNLOAD: (fileID: string, courseType: CourseType) => string;
export declare const LEARN_FILE_PREVIEW: (type: ContentType, fileID: string, courseType: CourseType, firstPageOnly?: boolean) => string;
export declare const LEARN_NOTIFICATION_LIST: (courseType: CourseType, expired: boolean) => string;
export declare const LEARN_NOTIFICATION_DETAIL: (courseID: string, notificationID: string, courseType: CourseType) => string;
export declare const LEARN_NOTIFICATION_EDIT: (courseType: CourseType) => string;
export declare const LEARN_HOMEWORK_LIST_NEW = "https://learn.tsinghua.edu.cn/b/wlxt/kczy/zy/student/zyListWj";
export declare const LEARN_HOMEWORK_LIST_SUBMITTED = "https://learn.tsinghua.edu.cn/b/wlxt/kczy/zy/student/zyListYjwg";
export declare const LEARN_HOMEWORK_LIST_GRADED = "https://learn.tsinghua.edu.cn/b/wlxt/kczy/zy/student/zyListYpg";
export declare const LEARN_HOMEWORK_LIST_EXCELLENT = "https://learn.tsinghua.edu.cn/b/wlxt/kczy/zy/student/yxzylist";
export declare const LEARN_HOMEWORK_LIST_SOURCE: {
    url: string;
    status: {
        submitted: boolean;
        graded: boolean;
    };
}[];
export declare const LEARN_HOMEWORK_PAGE: (courseID: string, id: string) => string;
export declare const LEARN_HOMEWORK_EXCELLENT_PAGE: (courseID: string, id: string) => string;
export declare const LEARN_HOMEWORK_DETAIL = "https://learn.tsinghua.edu.cn/b/wlxt/kczy/zy/student/detail";
export declare const LEARN_HOMEWORK_DETAIL_FORM_DATA: (baseId: string) => FormData;
export declare const LEARN_HOMEWORK_DOWNLOAD: (courseID: string, attachmentID: string) => string;
export declare const LEARN_HOMEWORK_SUBMIT_PAGE: (courseID: string, id: string) => string;
export declare const LEARN_HOMEWORK_SUBMIT: () => string;
export declare const LEARN_HOMEWORK_SUBMIT_FORM_DATA: (id: string, content?: string, attachment?: IHomeworkSubmitAttachment, removeAttachment?: boolean) => FormData;
export declare const LEARN_HOMEWORK_LIST_TEACHER = "https://learn.tsinghua.edu.cn/b/wlxt/kczy/zy/teacher/pageList";
export declare const LEARN_HOMEWORK_DETAIL_TEACHER: (courseID: string, homeworkID: string) => string;
export declare const LEARN_DISCUSSION_LIST: (courseID: string, courseType: CourseType) => string;
export declare const LEARN_DISCUSSION_DETAIL: (courseID: string, boardID: string, discussionID: string, courseType: CourseType, tabId?: number) => string;
export declare const LEARN_QUESTION_LIST_ANSWERED: (courseID: string, courseType: CourseType) => string;
export declare const LEARN_QUESTION_DETAIL: (courseID: string, questionID: string, courseType: CourseType) => string;
export declare const LEARN_QNR_LIST_ONGOING = "https://learn.tsinghua.edu.cn/b/wlxt/kcwj/wlkc_wjb/student/pageListWks";
export declare const LEARN_QNR_LIST_ENDED = "https://learn.tsinghua.edu.cn/b/wlxt/kcwj/wlkc_wjb/student/pageListYjs";
/** Note: This page is accessible even with an invalid `qnrID` as long as you have access to the given `courseID`. */
export declare const LEARN_QNR_SUBMIT_PAGE: (courseID: string, qnrID: string, type: QuestionnaireType) => string;
export declare const LEARN_QNR_DETAIL = "https://learn.tsinghua.edu.cn/b/wlxt/kcwj/wlkc_wjb/student/getWjnr";
export declare const LEARN_QNR_DETAIL_FORM: (courseID: string, qnrID: string) => FormData;
export declare const WebsiteShowLanguage: {
    zh: string;
    en: string;
};
export declare const LEARN_WEBSITE_LANGUAGE: (lang: Language) => string;
export declare const LEARN_FAVORITE_ADD: (type: ContentType, id: string) => string;
export declare const LEARN_FAVORITE_REMOVE: (id: string) => string;
export declare const LEARN_FAVORITE_LIST: (type?: ContentType) => string;
export declare const LEARN_FAVORITE_PIN = "https://learn.tsinghua.edu.cn/b/xt/wlkc_xsscb/student/addZd";
export declare const LEARN_FAVORITE_UNPIN = "https://learn.tsinghua.edu.cn/b/xt/wlkc_xsscb/student/delZd";
export declare const LEARN_FAVORITE_PIN_UNPIN_FORM_DATA: (id: string) => FormData;
export declare const LEARN_COMMENT_SET = "https://learn.tsinghua.edu.cn/b/wlxt/xt/wlkc_xsbjb/add";
export declare const LEARN_COMMENT_SET_FORM_DATA: (type: ContentType, id: string, content: string) => FormData;
export declare const LEARN_COMMENT_LIST: (type?: ContentType) => string;
export declare const LEARN_PAGE_LIST_FORM_DATA: (courseID?: string) => FormData;
export declare const LEARN_SORT_COURSES = "https://learn.tsinghua.edu.cn/b/wlxt/kc/wlkc_kcpxb/addorUpdate";
export declare const REGISTRAR_TICKET_FORM_DATA: () => FormData;
export declare const REGISTRAR_TICKET: () => string;
export declare const REGISTRAR_AUTH: (ticket: string) => string;
export declare const REGISTRAR_CALENDAR: (startDate: string, endDate: string, graduate?: boolean, callbackName?: string) => string;
//# sourceMappingURL=urls.d.ts.map